[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=root

[program:flask]
command=gunicorn --bind 0.0.0.0:%(ENV_APP_PORT)s --workers 2 --timeout 60 app:app
directory=/app
environment=FLASK_ENV=production
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
